<a href="https://colab.research.google.com/github/nadireus/Statistics-with-Python/blob/main/Statistics_with_Python1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import seaborn as sns


In [4]:
sns.get_dataset_names()

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'exercise',
 'flights',
 'fmri',
 'gammas',
 'geyser',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'tips',
 'titanic']

In [5]:
df = sns.load_dataset("mpg")

In [6]:
df.head(10)

mpg  cylinders  displacement  ...  model_year  origin                       name
0  18.0          8         307.0  ...          70     usa  chevrolet chevelle malibu
1  15.0          8         350.0  ...          70     usa          buick skylark 320
2  18.0          8         318.0  ...          70     usa         plymouth satellite
3  16.0          8         304.0  ...          70     usa              amc rebel sst
4  17.0          8         302.0  ...          70     usa                ford torino
5  15.0          8         429.0  ...          70     usa           ford galaxie 500
6  14.0          8         454.0  ...          70     usa           chevrolet impala
7  14.0          8         440.0  ...          70     usa          plymouth fury iii
8  14.0          8         455.0  ...          70     usa           pontiac catalina
9  15.0          8         390.0  ...          70     usa         amc ambassador dpl

[10 rows x 9 columns]

In [7]:
df.shape

(398, 9)

In [8]:
df.columns

Index(['mpg', 'cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'model_year', 'origin', 'name'],
      dtype='object')

In [9]:
len(df.columns)

9

In [10]:
df.shape[1]

9

In [11]:
df.info() #Print a concise summary of a DataFrame.This method prints information about a DataFrame includingthe index dtype and columns, non-null values and memory usage




<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64  
 2   displacement  398 non-null    float64
 3   horsepower    392 non-null    float64
 4   weight        398 non-null    int64  
 5   acceleration  398 non-null    float64
 6   model_year    398 non-null    int64  
 7   origin        398 non-null    object 
 8   name          398 non-null    object 
dtypes: float64(4), int64(3), object(2)
memory usage: 28.1+ KB


In [12]:
df.select_dtypes(include=["object"])

origin                       name
0       usa  chevrolet chevelle malibu
1       usa          buick skylark 320
2       usa         plymouth satellite
3       usa              amc rebel sst
4       usa                ford torino
..      ...                        ...
393     usa            ford mustang gl
394  europe                  vw pickup
395     usa              dodge rampage
396     usa                ford ranger
397     usa                 chevy s-10

[398 rows x 2 columns]

In [13]:
df.select_dtypes(exclude=["object"])

mpg  cylinders  displacement  ...  weight  acceleration  model_year
0    18.0          8         307.0  ...    3504          12.0          70
1    15.0          8         350.0  ...    3693          11.5          70
2    18.0          8         318.0  ...    3436          11.0          70
3    16.0          8         304.0  ...    3433          12.0          70
4    17.0          8         302.0  ...    3449          10.5          70
..    ...        ...           ...  ...     ...           ...         ...
393  27.0          4         140.0  ...    2790          15.6          82
394  44.0          4          97.0  ...    2130          24.6          82
395  32.0          4         135.0  ...    2295          11.6          82
396  28.0          4         120.0  ...    2625          18.6          82
397  31.0          4         119.0  ...    2720          19.4          82

[398 rows x 7 columns]

In [15]:
#in order to check uniq values
df.nunique(axis=0)

mpg             129
cylinders         5
displacement     82
horsepower       93
weight          351
acceleration     95
model_year       13
origin            3
name            305
dtype: int64

In [ ]:
df.plot.pie(y)

In [ ]:
df.describe()

Population and 

In [16]:
import numpy as np

In [18]:
np.random.seed(101)
population = np.random.randint(0,100, size = 100000)

In [19]:
population

array([95, 11, 81, ..., 72, 75, 64])

In [20]:
len(population)

100000

In [21]:
np.random.seed(101)
sample = np.random.choice(population, 100)

In [ ]:

sample = np.random.choice(population, 100)

In [23]:
np.random.seed(51)
sample = np.random.choice(population, 100)

In [ ]:
sample

In [24]:
sample

array([89, 69,  3, 24, 28,  1, 63, 44, 41, 23,  1, 53, 21, 23, 51, 90, 26,
       54, 84, 83,  9, 64, 42, 15, 65, 37,  3, 29, 96, 90, 47, 73, 92, 87,
       91, 67, 69, 14, 45, 11, 68, 70, 95, 21, 64, 77, 94, 63, 55, 36, 21,
       46, 77, 82, 27, 89, 16, 97, 70, 85, 71, 50, 32, 99, 16, 34, 62, 87,
       48, 37, 46, 25, 53,  4, 58, 18, 59, 68, 68, 90, 23, 56, 17, 86, 24,
       47, 59,  6, 87, 38,  7, 96, 39, 50, 33, 13, 21,  4, 13, 43])

In [22]:
sample

array([48, 99, 63, 36, 99, 38, 76, 63, 91, 53, 75, 62, 23, 13,  8, 83, 10,
       15, 80,  8, 56,  6, 85, 87, 22, 97, 51, 26, 75, 47, 86, 21, 10, 90,
       31, 66, 30, 66, 63,  8, 89, 24, 79, 45,  9,  1, 54, 91, 58,  4, 89,
        1, 38, 55, 21, 28, 43, 26, 23, 85, 98, 52, 19, 99, 56, 16, 87, 10,
       64, 44, 44, 71, 84, 83, 76, 47, 41, 54, 71,  7,  1, 17, 61, 35, 57,
       95, 87, 67, 52, 91, 68, 14, 88, 77, 96, 39,  5, 27, 40, 49])

In [25]:
population.mean()

49.41751

In [26]:
sample.mean()

49.57

In [30]:
#sampling distribution
sample_means = []

for i in range (100) :
    sample = np.random.choice(population, 100)
    sample_means.append(sample.mean())
sample_means

[47.73,
 46.72,
 54.82,
 50.55,
 51.24,
 45.67,
 42.04,
 51.32,
 46.44,
 48.69,
 46.76,
 48.94,
 56.45,
 50.32,
 52.38,
 48.92,
 48.09,
 44.35,
 47.15,
 54.11,
 51.0,
 46.81,
 50.57,
 51.64,
 48.55,
 48.61,
 48.37,
 49.99,
 50.78,
 48.61,
 47.59,
 47.5,
 47.63,
 45.57,
 49.17,
 50.64,
 46.5,
 48.33,
 51.81,
 43.47,
 47.51,
 45.23,
 44.84,
 49.07,
 51.78,
 47.99,
 45.7,
 49.73,
 44.84,
 52.04,
 47.99,
 47.32,
 50.32,
 51.07,
 51.38,
 51.81,
 48.66,
 43.32,
 43.39,
 52.65,
 48.46,
 47.55,
 51.8,
 49.14,
 50.33,
 44.8,
 45.29,
 43.67,
 45.64,
 49.17,
 49.25,
 46.2,
 49.31,
 50.11,
 49.99,
 46.09,
 52.41,
 51.74,
 55.79,
 50.93,
 44.67,
 49.36,
 47.29,
 52.17,
 50.48,
 49.58,
 55.03,
 52.55,
 51.03,
 51.99,
 51.14,
 46.94,
 47.84,
 48.28,
 48.73,
 45.11,
 49.59,
 52.34,
 46.25,
 51.54]

In [31]:
np.mean(sample_means)

48.920500000000004